version: 2
jobs:
  build:
    working_directory: ~/tic-tac-toe
    docker:
      - image: circleci/node:6-browsers
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: building
          command: yarn build
